# pandas: Reshape DataFrame from Wide Format to Long Format

## Package Import

In [1]:
import pandas as pd
import numpy as np

## Dataset Import

The dataset used in this notebook is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

## Reshape a DataFrame from wide format to long format

What if we want 'HP' and 'Attack' to be the values of the column named 'Stats'?

In [3]:
f = data[['Name', 'HP', 'Attack']].iloc[:5]
f

                    Name  HP  Attack
0              Bulbasaur  45      49
1                Ivysaur  60      62
2               Venusaur  80      82
3  VenusaurMega Venusaur  80     100
4             Charmander  39      52

In [4]:
f.melt(id_vars='Name', var_name='Stats', value_name='Points')

                    Name   Stats  Points
0              Bulbasaur      HP      45
1                Ivysaur      HP      60
2               Venusaur      HP      80
3  VenusaurMega Venusaur      HP      80
4             Charmander      HP      39
5              Bulbasaur  Attack      49
6                Ivysaur  Attack      62
7               Venusaur  Attack      82
8  VenusaurMega Venusaur  Attack     100
9             Charmander  Attack      52