# pandas:  Reset index

In [1]:
import pandas as pd

## Loading data into Pandas DataFrame
The dataset is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

In the cell below, you can see the index is not consecutive (the leftmost column). We can reset it with the `reset_index()` method. By default, it adds the old index as a new column. If you do not want that, use the `drop=True` parameter.

In [3]:
new_data = data.loc[(data['Type 1'] == 'Grass') | (data['Type 2'] == 'Poison')][0::10].loc[data['HP'] > 50].head(3)
new_data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False

In [4]:
new_data.reset_index(drop=True, inplace=True)
new_data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
1,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
2,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False