# pandas: Reverse Row/Column Order

## Package Import

In [1]:
import pandas as pd
import numpy as np

## Dataset Import

The dataset used in this notebook is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

In [3]:
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Reverse Row/Column Order

See also `iloc` [here](https://cornel05.github.io/cornel.ai/notebooks/snippets/pandas/basic_pandas/basic_pandas_1.html#iloc-and-loc-in-pandas)

In [4]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Row

In [5]:
data.iloc[::-1].head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

See also `reset_index` [here](https://cornel05.github.io/cornel.ai/notebooks/snippets/pandas/basic_pandas/basic_pandas_1.html#reset-index).

In [6]:
data.iloc[::-1].reset_index().head()

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
1,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
2,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
3,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
4,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

In [7]:
data.iloc[::-1].reset_index(drop=True).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
1,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
2,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
3,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
4,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

### Column

In [8]:
data.iloc[:, ::-1].head()

,Legendary,Generation,Speed,Sp. Def,Sp. Atk,Defense,Attack,HP,Total,Type 2,Type 1,Name,#
0,False,1,45,65,65,49,49,45,318,Poison,Grass,Bulbasaur,1
1,False,1,60,80,80,63,62,60,405,Poison,Grass,Ivysaur,2
2,False,1,80,100,100,83,82,80,525,Poison,Grass,Venusaur,3
3,False,1,80,120,122,123,100,80,625,Poison,Grass,VenusaurMega Venusaur,3
4,False,1,65,50,60,43,52,39,309,NaN,Fire,Charmander,4