# pandas: Reshape DataFrame from Wide Format to Long Format

## Package Import

In [1]:
import pandas as pd
import numpy as np

## Dataset Import

The dataset used in this notebook is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

In [3]:
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Reshape a DataFrame from wide format to long format

What if we want 'HP' and 'Attack' to be the values of the column named 'Stats'?

In [4]:
f = data[['Name', 'HP', 'Attack']].iloc[:5]
f

                    Name  HP  Attack
0              Bulbasaur  45      49
1                Ivysaur  60      62
2               Venusaur  80      82
3  VenusaurMega Venusaur  80     100
4             Charmander  39      52

In [5]:
f.melt(id_vars='Name', var_name='Stats', value_name='Points')

                    Name   Stats  Points
0              Bulbasaur      HP      45
1                Ivysaur      HP      60
2               Venusaur      HP      80
3  VenusaurMega Venusaur      HP      80
4             Charmander      HP      39
5              Bulbasaur  Attack      49
6                Ivysaur  Attack      62
7               Venusaur  Attack      82
8  VenusaurMega Venusaur  Attack     100
9             Charmander  Attack      52